project_id = "rtvcsywkkcgakfzsuxgz"

[functions.sync-twizzit-events]
verify_jwt = false

[functions.sync-twizzit-teams]
verify_jwt = false

[functions.bulk-insert-sponsors]
verify_jwt = false

[functions.fetch-instagram-posts]
verify_jwt = false

[functions.refresh-instagram-token]
verify_jwt = false

[functions.get-cron-status]
verify_jwt = false